// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG0N-Ty8OylYVzPMaGYX_YSSiAlKuLXm0',
    appId: '1:426456494653:web:f7d26a2dfcea0a329af054',
    messagingSenderId: '426456494653',
    projectId: 'kinesia-app',
    authDomain: 'kinesia-app.firebaseapp.com',
    storageBucket: 'kinesia-app.firebasestorage.app',
    measurementId: 'G-PCLHC9235R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdr5Qi_bnQA-plsZAfVrilOWJNOWq91dU',
    appId: '1:426456494653:android:cef296e264d3fa539af054',
    messagingSenderId: '426456494653',
    projectId: 'kinesia-app',
    storageBucket: 'kinesia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDONXNnasBuGOlutz93zZC7L2sGfSuLCE',
    appId: '1:426456494653:ios:ad6d5f0a759b14239af054',
    messagingSenderId: '426456494653',
    projectId: 'kinesia-app',
    storageBucket: 'kinesia-app.firebasestorage.app',
    iosClientId: '426456494653-f4a2hj54hhnrkeqqnhncpb7e30slg0qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kinesiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDONXNnasBuGOlutz93zZC7L2sGfSuLCE',
    appId: '1:426456494653:ios:ad6d5f0a759b14239af054',
    messagingSenderId: '426456494653',
    projectId: 'kinesia-app',
    storageBucket: 'kinesia-app.firebasestorage.app',
    iosClientId: '426456494653-f4a2hj54hhnrkeqqnhncpb7e30slg0qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.kinesiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG0N-Ty8OylYVzPMaGYX_YSSiAlKuLXm0',
    appId: '1:426456494653:web:d04438a003b939cd9af054',
    messagingSenderId: '426456494653',
    projectId: 'kinesia-app',
    authDomain: 'kinesia-app.firebaseapp.com',
    storageBucket: 'kinesia-app.firebasestorage.app',
    measurementId: 'G-D7G61CBX81',
  );
}
